java_library(
    name = "singlepixelsensorplugin",
    srcs = [
        "SinglePixelSensorPlugin.java",
    ],
    deps = [
        "@multikinect//src/main/java/edu/bu/vip/multikinect/controller/plugin:plugin",
    ],
)
