load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

package(
    default_visibility = ["//visibility:public"],
)

java_proto_library(
    name = "singlepixel",
    proto_deps = [
        "//thirdparty/protobuf/google/protobuf:well_known_types",
    ],
    protos = [
        "singlepixel.proto",
    ],
)
