package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "readingutils",
    srcs = [
        "ReadingUtils.java",
    ],
    deps = [
        "//src/main/proto:singlepixel_java",
    ],
)
