# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/proto/realtime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import frame_pb2 as src_dot_main_dot_proto_dot_frame__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/main/proto/realtime.proto',
  package='bu.vip.multikinect.controller.realtime',
  syntax='proto3',
  serialized_pb=_b('\n\x1dsrc/main/proto/realtime.proto\x12&bu.vip.multikinect.controller.realtime\x1a\x1asrc/main/proto/frame.proto\"\xa8\x01\n\x0bSyncedFrame\x12K\n\tskeletons\x18\x01 \x03(\x0b\x32\x38.bu.vip.multikinect.controller.realtime.CombinedSkeleton\x12L\n\x0c\x66rame_points\x18\x02 \x03(\x0b\x32\x36.bu.vip.multikinect.controller.realtime.FrameDataPoint\"5\n\x0e\x46rameDataPoint\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\"\x9e\x01\n\x10\x43ombinedSkeleton\x12\n\n\x02id\x18\x01 \x01(\x04\x12.\n\x08skeleton\x18\x02 \x01(\x0b\x32\x1c.bu.vip.multikinect.Skeleton\x12N\n\x0b\x64\x61ta_points\x18\x03 \x03(\x0b\x32\x39.bu.vip.multikinect.controller.realtime.SkeletonDataPoint\";\n\x11SkeletonDataPoint\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x13\n\x0bskeleton_id\x18\x02 \x01(\x04\x42/\n%edu.bu.vip.kinect.controller.realtimeB\x06Protosb\x06proto3')
  ,
  dependencies=[src_dot_main_dot_proto_dot_frame__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SYNCEDFRAME = _descriptor.Descriptor(
  name='SyncedFrame',
  full_name='bu.vip.multikinect.controller.realtime.SyncedFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skeletons', full_name='bu.vip.multikinect.controller.realtime.SyncedFrame.skeletons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_points', full_name='bu.vip.multikinect.controller.realtime.SyncedFrame.frame_points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=270,
)


_FRAMEDATAPOINT = _descriptor.Descriptor(
  name='FrameDataPoint',
  full_name='bu.vip.multikinect.controller.realtime.FrameDataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='bu.vip.multikinect.controller.realtime.FrameDataPoint.camera_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='bu.vip.multikinect.controller.realtime.FrameDataPoint.frame_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=325,
)


_COMBINEDSKELETON = _descriptor.Descriptor(
  name='CombinedSkeleton',
  full_name='bu.vip.multikinect.controller.realtime.CombinedSkeleton',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bu.vip.multikinect.controller.realtime.CombinedSkeleton.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skeleton', full_name='bu.vip.multikinect.controller.realtime.CombinedSkeleton.skeleton', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_points', full_name='bu.vip.multikinect.controller.realtime.CombinedSkeleton.data_points', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=486,
)


_SKELETONDATAPOINT = _descriptor.Descriptor(
  name='SkeletonDataPoint',
  full_name='bu.vip.multikinect.controller.realtime.SkeletonDataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='bu.vip.multikinect.controller.realtime.SkeletonDataPoint.camera_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skeleton_id', full_name='bu.vip.multikinect.controller.realtime.SkeletonDataPoint.skeleton_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=547,
)

_SYNCEDFRAME.fields_by_name['skeletons'].message_type = _COMBINEDSKELETON
_SYNCEDFRAME.fields_by_name['frame_points'].message_type = _FRAMEDATAPOINT
_COMBINEDSKELETON.fields_by_name['skeleton'].message_type = src_dot_main_dot_proto_dot_frame__pb2._SKELETON
_COMBINEDSKELETON.fields_by_name['data_points'].message_type = _SKELETONDATAPOINT
DESCRIPTOR.message_types_by_name['SyncedFrame'] = _SYNCEDFRAME
DESCRIPTOR.message_types_by_name['FrameDataPoint'] = _FRAMEDATAPOINT
DESCRIPTOR.message_types_by_name['CombinedSkeleton'] = _COMBINEDSKELETON
DESCRIPTOR.message_types_by_name['SkeletonDataPoint'] = _SKELETONDATAPOINT

SyncedFrame = _reflection.GeneratedProtocolMessageType('SyncedFrame', (_message.Message,), dict(
  DESCRIPTOR = _SYNCEDFRAME,
  __module__ = 'src.main.proto.realtime_pb2'
  # @@protoc_insertion_point(class_scope:bu.vip.multikinect.controller.realtime.SyncedFrame)
  ))
_sym_db.RegisterMessage(SyncedFrame)

FrameDataPoint = _reflection.GeneratedProtocolMessageType('FrameDataPoint', (_message.Message,), dict(
  DESCRIPTOR = _FRAMEDATAPOINT,
  __module__ = 'src.main.proto.realtime_pb2'
  # @@protoc_insertion_point(class_scope:bu.vip.multikinect.controller.realtime.FrameDataPoint)
  ))
_sym_db.RegisterMessage(FrameDataPoint)

CombinedSkeleton = _reflection.GeneratedProtocolMessageType('CombinedSkeleton', (_message.Message,), dict(
  DESCRIPTOR = _COMBINEDSKELETON,
  __module__ = 'src.main.proto.realtime_pb2'
  # @@protoc_insertion_point(class_scope:bu.vip.multikinect.controller.realtime.CombinedSkeleton)
  ))
_sym_db.RegisterMessage(CombinedSkeleton)

SkeletonDataPoint = _reflection.GeneratedProtocolMessageType('SkeletonDataPoint', (_message.Message,), dict(
  DESCRIPTOR = _SKELETONDATAPOINT,
  __module__ = 'src.main.proto.realtime_pb2'
  # @@protoc_insertion_point(class_scope:bu.vip.multikinect.controller.realtime.SkeletonDataPoint)
  ))
_sym_db.RegisterMessage(SkeletonDataPoint)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%edu.bu.vip.kinect.controller.realtimeB\006Protos'))
# @@protoc_insertion_point(module_scope)
