# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/proto/singlepixel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/main/proto/singlepixel.proto',
  package='bu.vip.singlepixel',
  syntax='proto3',
  serialized_pb=_b('\n src/main/proto/singlepixel.proto\x12\x12\x62u.vip.singlepixel\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n\x18SinglePixelSensorReading\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x0b\n\x03red\x18\x03 \x01(\x01\x12\r\n\x05green\x18\x04 \x01(\x01\x12\x0c\n\x04\x62lue\x18\x05 \x01(\x01\x12\r\n\x05\x63lear\x18\x06 \x01(\x01\x12\x34\n\x10ntp_capture_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB \n\x16\x65\x64u.bu.vip.singlepixelB\x06Protosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SINGLEPIXELSENSORREADING = _descriptor.Descriptor(
  name='SinglePixelSensorReading',
  full_name='bu.vip.singlepixel.SinglePixelSensorReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='bu.vip.singlepixel.SinglePixelSensorReading.group_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='bu.vip.singlepixel.SinglePixelSensorReading.sensor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='red', full_name='bu.vip.singlepixel.SinglePixelSensorReading.red', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='green', full_name='bu.vip.singlepixel.SinglePixelSensorReading.green', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blue', full_name='bu.vip.singlepixel.SinglePixelSensorReading.blue', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clear', full_name='bu.vip.singlepixel.SinglePixelSensorReading.clear', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ntp_capture_time', full_name='bu.vip.singlepixel.SinglePixelSensorReading.ntp_capture_time', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=264,
)

_SINGLEPIXELSENSORREADING.fields_by_name['ntp_capture_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SinglePixelSensorReading'] = _SINGLEPIXELSENSORREADING

SinglePixelSensorReading = _reflection.GeneratedProtocolMessageType('SinglePixelSensorReading', (_message.Message,), dict(
  DESCRIPTOR = _SINGLEPIXELSENSORREADING,
  __module__ = 'src.main.proto.singlepixel_pb2'
  # @@protoc_insertion_point(class_scope:bu.vip.singlepixel.SinglePixelSensorReading)
  ))
_sym_db.RegisterMessage(SinglePixelSensorReading)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026edu.bu.vip.singlepixelB\006Protos'))
# @@protoc_insertion_point(module_scope)
